// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringApp;

#nullable disable

namespace MonitoringApp.Migrations
{
    [DbContext(typeof(AlertDbContext))]
    partial class AlertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringApp.AlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("FiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MonitorCondition")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SearchResultsUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("AlertId", "MonitorCondition");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.AlertRule", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("AlertNameContains").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("ApplyToTarget").HasColumnType("bit");
                    b.Property<string>("CategoryName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("Collapsed").HasColumnType("bit");
                    b.Property<string>("ConditionType").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<bool>("Enabled").HasColumnType("bit");
                    b.Property<string>("FailedItemName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("InventoryRole").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("IsCritical").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<int>("Priority").HasColumnType("int");
                    b.Property<string>("QueryResultType").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("RuleType").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<int>("Threshold").HasColumnType("int");
                    b.Property<string>("Tone").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.HasIndex("Enabled", "Priority");
                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.ComputerInventoryEntry", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Computer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResourceGroup")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Site")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SubscriptionId", "Computer");

                    b.ToTable("ComputerInventory", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.DatabaseSetting", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.ParsedAlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AlertName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FiredDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InventoryComputer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InventorySubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<string>("MonitorCondition")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OriginalAlertId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("QueryResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("InventorySubscriptionId", "InventoryComputer");

                    b.ToTable("ParsedAlerts", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.SqlAuthenticationUser", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Username");

                    b.ToTable("AuthenticationUsers", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.ParsedAlertRecord", b =>
                {
                    b.HasOne("MonitoringApp.AlertRecord", "Alert")
                        .WithOne()
                        .HasForeignKey("MonitoringApp.ParsedAlertRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringApp.ComputerInventoryEntry", "InventoryComputerEntry")
                        .WithMany("ParsedAlerts")
                        .HasForeignKey("InventorySubscriptionId", "InventoryComputer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alert");

                    b.Navigation("InventoryComputerEntry");
                });

            modelBuilder.Entity("MonitoringApp.ComputerInventoryEntry", b =>
                {
                    b.Navigation("ParsedAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
